image:
  file: .gitpod.Dockerfile

tasks:
  - name: Install Python project with dependencies
    # Do not use `python -m pip install` with pyenv,
    # see https://github.com/pyenv/pyenv/issues/2243
    init: |
      uv pip install -r requirements.txt --system

  - name: Launch MinIO server
    init: |
      mkdir -p /workspace/data
      minio server /workspace/data &
    command: |
      minio server --address :9010 --console-address :19010 /workspace/data

  - name: Launch Ollama
    command: |
      ollama serve

ports:
  - port: 19010
